
    - name: creating the file
      ansible.builtin.file:
        path: /home/test-file
        state: touch

    - name: installing specific version file 
      ansible.builtin.command: curl -sL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup.sh
      
    
    - name: Run NodeJS 20 setup script
      ansible.builtin.command: bash /tmp/nodesource_setup.sh
      become: yes

    - name: Install NodeJS 20
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Creating the system user
      ansible.builtin.user  :
        name: sandeep-user
        system: yes
        home: /app
        shell : /sbin/nologin    #expictly prevents user to login 
        comment : "System user"


    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory
        mode : '0755'
        

    - name: Download catalogue zip using curl
      ansible.builtin.command: curl -sL https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip  -o /tmp/user-v3.zip
      become: yes


##installing unzip package explictly because it is ubuntu 
    - name: installing unzip package   
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: unzipping the package into /app  #unacheive comes from unzip
      ansible.builtin.unarchive:
        src: /tmp/user-v3.zip
        dest: /app
        remote_src: yes
        
    
    - name: installing npm packages
      ansible.builtin.npm:
        path: /app
        state: present

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        name: user.service
        path: /etc/systemd/system
        state: directory

    - name: Copy the systemd service file
      ansible.builtin.copy:
        src: user-file                             # file on control node
        dest: /etc/systemd/system/user.service
        owner: root


    - name: daemon_reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enabling the user
      ansible.builtin.service:
        name: user.service
        state: started
        enabled: yes