- name: creating a user
  hosts: ubuntu
  become: yes 

  tasks: 





- name: user is there or not
  ansible.builtin.command:
   id Roboshop
  regisgter: src_out_put_file
  ignore_erros : yes 


- name: printing the output 
  ansible.builtin.debug:
    msg: this is the user {{src_out_put_file}}