- name: Installing packages
  hosts: web
  become: true

  tasks:
    - name: Installing the packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql
        - nginx
        - zip
