- name: ping the server
  hosts: web
  tasks:
    - name: ping the web server
      ansible.builtin.ping:

    - name: print success message
      ansible.builtin.debug:
        msg: "ping successful"